//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvseumDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class @base : ModellBase
    {
        private int _bASE_ID;
    	public int BASE_ID 
    	{ 
    		get { return _bASE_ID; } 
    		set
    		{
    			if (value != _bASE_ID) {
    				_bASE_ID = value;
    				 OnPropertyChanged("BASE_ID");
    			}
    		} 
    	}
    
        private Nullable<System.DateTime> _fROM_DATE;
    	public Nullable<System.DateTime> FROM_DATE 
    	{ 
    		get { return _fROM_DATE; } 
    		set
    		{
    			if (value != _fROM_DATE) {
    				_fROM_DATE = value;
    				 OnPropertyChanged("FROM_DATE");
    			}
    		} 
    	}
    
        private Nullable<System.DateTime> _tO_DATE;
    	public Nullable<System.DateTime> TO_DATE 
    	{ 
    		get { return _tO_DATE; } 
    		set
    		{
    			if (value != _tO_DATE) {
    				_tO_DATE = value;
    				 OnPropertyChanged("TO_DATE");
    			}
    		} 
    	}
    
        private string _dESCRIPTION;
    	public string DESCRIPTION 
    	{ 
    		get { return _dESCRIPTION; } 
    		set
    		{
    			if (value != _dESCRIPTION) {
    				_dESCRIPTION = value;
    				 OnPropertyChanged("DESCRIPTION");
    			}
    		} 
    	}
    
        private string _uSE_COMMENT;
    	public string USE_COMMENT 
    	{ 
    		get { return _uSE_COMMENT; } 
    		set
    		{
    			if (value != _uSE_COMMENT) {
    				_uSE_COMMENT = value;
    				 OnPropertyChanged("USE_COMMENT");
    			}
    		} 
    	}
    
        private string _cRU;
    	public string CRU 
    	{ 
    		get { return _cRU; } 
    		set
    		{
    			if (value != _cRU) {
    				_cRU = value;
    				 OnPropertyChanged("CRU");
    			}
    		} 
    	}
    
        private System.DateTime _cRD;
    	public System.DateTime CRD 
    	{ 
    		get { return _cRD; } 
    		set
    		{
    			if (value != _cRD) {
    				_cRD = value;
    				 OnPropertyChanged("CRD");
    			}
    		} 
    	}
    
        private string _mDU;
    	public string MDU 
    	{ 
    		get { return _mDU; } 
    		set
    		{
    			if (value != _mDU) {
    				_mDU = value;
    				 OnPropertyChanged("MDU");
    			}
    		} 
    	}
    
        private System.DateTime _mDD;
    	public System.DateTime MDD 
    	{ 
    		get { return _mDD; } 
    		set
    		{
    			if (value != _mDD) {
    				_mDD = value;
    				 OnPropertyChanged("MDD");
    			}
    		} 
    	}
    
    }
}
