//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvseumDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class dm_super_type : ModellBase
    {
        public dm_super_type()
        {
            this.dm_super_type1 = new HashSet<dm_super_type>();
        }
    
        private int _sUPER_TYPE_ID;
    	public int SUPER_TYPE_ID 
    	{ 
    		get { return _sUPER_TYPE_ID; } 
    		set
    		{
    			if (value != _sUPER_TYPE_ID) {
    				_sUPER_TYPE_ID = value;
    				 OnPropertyChanged("SUPER_TYPE_ID");
    			}
    		} 
    	}
    
        private Nullable<int> _bASE_ID;
    	public Nullable<int> BASE_ID 
    	{ 
    		get { return _bASE_ID; } 
    		set
    		{
    			if (value != _bASE_ID) {
    				_bASE_ID = value;
    				 OnPropertyChanged("BASE_ID");
    			}
    		} 
    	}
    
        private Nullable<int> _gROUP_ID;
    	public Nullable<int> GROUP_ID 
    	{ 
    		get { return _gROUP_ID; } 
    		set
    		{
    			if (value != _gROUP_ID) {
    				_gROUP_ID = value;
    				 OnPropertyChanged("GROUP_ID");
    			}
    		} 
    	}
    
        private string _sUPER_TYPE_NAME;
    	public string SUPER_TYPE_NAME 
    	{ 
    		get { return _sUPER_TYPE_NAME; } 
    		set
    		{
    			if (value != _sUPER_TYPE_NAME) {
    				_sUPER_TYPE_NAME = value;
    				 OnPropertyChanged("SUPER_TYPE_NAME");
    			}
    		} 
    	}
    
        private string _sUPER_TYPE_SHORT_NAME;
    	public string SUPER_TYPE_SHORT_NAME 
    	{ 
    		get { return _sUPER_TYPE_SHORT_NAME; } 
    		set
    		{
    			if (value != _sUPER_TYPE_SHORT_NAME) {
    				_sUPER_TYPE_SHORT_NAME = value;
    				 OnPropertyChanged("SUPER_TYPE_SHORT_NAME");
    			}
    		} 
    	}
    
        private string _sOPTIONAL;
    	public string SOPTIONAL 
    	{ 
    		get { return _sOPTIONAL; } 
    		set
    		{
    			if (value != _sOPTIONAL) {
    				_sOPTIONAL = value;
    				 OnPropertyChanged("SOPTIONAL");
    			}
    		} 
    	}
    
    
        public virtual ICollection<dm_super_type> dm_super_type1 { get; set; }
        public virtual dm_super_type dm_super_type2 { get; set; }
    }
}
