//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvseumDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventoryparam : ModellBase
    {
        private int _inventoryParamID;
    	public int InventoryParamID 
    	{ 
    		get { return _inventoryParamID; } 
    		set
    		{
    			if (value != _inventoryParamID) {
    				_inventoryParamID = value;
    				 OnPropertyChanged("InventoryParamID");
    			}
    		} 
    	}
    
        private Nullable<int> _inventoryID;
    	public Nullable<int> InventoryID 
    	{ 
    		get { return _inventoryID; } 
    		set
    		{
    			if (value != _inventoryID) {
    				_inventoryID = value;
    				 OnPropertyChanged("InventoryID");
    			}
    		} 
    	}
    
        private Nullable<int> _sUPER_TYPE_ID;
    	public Nullable<int> SUPER_TYPE_ID 
    	{ 
    		get { return _sUPER_TYPE_ID; } 
    		set
    		{
    			if (value != _sUPER_TYPE_ID) {
    				_sUPER_TYPE_ID = value;
    				 OnPropertyChanged("SUPER_TYPE_ID");
    			}
    		} 
    	}
    
        private Nullable<int> _pARAM_VALUE_ID;
    	public Nullable<int> PARAM_VALUE_ID 
    	{ 
    		get { return _pARAM_VALUE_ID; } 
    		set
    		{
    			if (value != _pARAM_VALUE_ID) {
    				_pARAM_VALUE_ID = value;
    				 OnPropertyChanged("PARAM_VALUE_ID");
    			}
    		} 
    	}
    
        private string _pARAM_VALUE;
    	public string PARAM_VALUE 
    	{ 
    		get { return _pARAM_VALUE; } 
    		set
    		{
    			if (value != _pARAM_VALUE) {
    				_pARAM_VALUE = value;
    				 OnPropertyChanged("PARAM_VALUE");
    			}
    		} 
    	}
    
    }
}
