//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvseumDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventoryno : ModellBase
    {
        private int _inventoryNoId;
    	public int InventoryNoId 
    	{ 
    		get { return _inventoryNoId; } 
    		set
    		{
    			if (value != _inventoryNoId) {
    				_inventoryNoId = value;
    				 OnPropertyChanged("InventoryNoId");
    			}
    		} 
    	}
    
        private Nullable<int> _bASE_ID;
    	public Nullable<int> BASE_ID 
    	{ 
    		get { return _bASE_ID; } 
    		set
    		{
    			if (value != _bASE_ID) {
    				_bASE_ID = value;
    				 OnPropertyChanged("BASE_ID");
    			}
    		} 
    	}
    
        private Nullable<int> _year;
    	public Nullable<int> Year 
    	{ 
    		get { return _year; } 
    		set
    		{
    			if (value != _year) {
    				_year = value;
    				 OnPropertyChanged("Year");
    			}
    		} 
    	}
    
        private Nullable<int> _tetel;
    	public Nullable<int> Tetel 
    	{ 
    		get { return _tetel; } 
    		set
    		{
    			if (value != _tetel) {
    				_tetel = value;
    				 OnPropertyChanged("Tetel");
    			}
    		} 
    	}
    
        private Nullable<int> _sor;
    	public Nullable<int> Sor 
    	{ 
    		get { return _sor; } 
    		set
    		{
    			if (value != _sor) {
    				_sor = value;
    				 OnPropertyChanged("Sor");
    			}
    		} 
    	}
    
        private Nullable<int> _al;
    	public Nullable<int> Al 
    	{ 
    		get { return _al; } 
    		set
    		{
    			if (value != _al) {
    				_al = value;
    				 OnPropertyChanged("Al");
    			}
    		} 
    	}
    
        private Nullable<int> _ryear;
    	public Nullable<int> Ryear 
    	{ 
    		get { return _ryear; } 
    		set
    		{
    			if (value != _ryear) {
    				_ryear = value;
    				 OnPropertyChanged("Ryear");
    			}
    		} 
    	}
    
        private string _rInventoryNo;
    	public string RInventoryNo 
    	{ 
    		get { return _rInventoryNo; } 
    		set
    		{
    			if (value != _rInventoryNo) {
    				_rInventoryNo = value;
    				 OnPropertyChanged("RInventoryNo");
    			}
    		} 
    	}
    
    }
}
