//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvseumDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class iventoryparamrule : ModellBase
    {
        private int _iventoryParamRuleId;
    	public int IventoryParamRuleId 
    	{ 
    		get { return _iventoryParamRuleId; } 
    		set
    		{
    			if (value != _iventoryParamRuleId) {
    				_iventoryParamRuleId = value;
    				 OnPropertyChanged("IventoryParamRuleId");
    			}
    		} 
    	}
    
        private Nullable<int> _bASE_ID;
    	public Nullable<int> BASE_ID 
    	{ 
    		get { return _bASE_ID; } 
    		set
    		{
    			if (value != _bASE_ID) {
    				_bASE_ID = value;
    				 OnPropertyChanged("BASE_ID");
    			}
    		} 
    	}
    
        private Nullable<int> _collectionId;
    	public Nullable<int> CollectionId 
    	{ 
    		get { return _collectionId; } 
    		set
    		{
    			if (value != _collectionId) {
    				_collectionId = value;
    				 OnPropertyChanged("CollectionId");
    			}
    		} 
    	}
    
        private Nullable<int> _paramId;
    	public Nullable<int> ParamId 
    	{ 
    		get { return _paramId; } 
    		set
    		{
    			if (value != _paramId) {
    				_paramId = value;
    				 OnPropertyChanged("ParamId");
    			}
    		} 
    	}
    
        private Nullable<int> _paramTypeId;
    	public Nullable<int> ParamTypeId 
    	{ 
    		get { return _paramTypeId; } 
    		set
    		{
    			if (value != _paramTypeId) {
    				_paramTypeId = value;
    				 OnPropertyChanged("ParamTypeId");
    			}
    		} 
    	}
    
        private Nullable<int> _orderNo;
    	public Nullable<int> OrderNo 
    	{ 
    		get { return _orderNo; } 
    		set
    		{
    			if (value != _orderNo) {
    				_orderNo = value;
    				 OnPropertyChanged("OrderNo");
    			}
    		} 
    	}
    
        private Nullable<int> _orderSign;
    	public Nullable<int> OrderSign 
    	{ 
    		get { return _orderSign; } 
    		set
    		{
    			if (value != _orderSign) {
    				_orderSign = value;
    				 OnPropertyChanged("OrderSign");
    			}
    		} 
    	}
    
    }
}
