//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvseumDal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvsevmMySqlEntities : DbContext
    {
        public MvsevmMySqlEntities()
            : base("name=MvsevmMySqlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<@base> @base { get; set; }
        public DbSet<dm_super_type> dm_super_type { get; set; }
        public DbSet<inventory> inventory { get; set; }
        public DbSet<inventoryno> inventoryno { get; set; }
        public DbSet<inventoryparam> inventoryparam { get; set; }
        public DbSet<iventoryparamrule> iventoryparamrule { get; set; }
        public DbSet<subject> subject { get; set; }
        public DbSet<subjectparam> subjectparam { get; set; }
        public DbSet<subjectparamrule> subjectparamrule { get; set; }
        public DbSet<tezaurusz> tezaurusz { get; set; }
        public DbSet<tezauruszrel> tezauruszrel { get; set; }
        public DbSet<v_dm_super_type> v_dm_super_type { get; set; }
    }
}
