//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvseumDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tezaurusz : ModellBase
    {
        private int _tezaurusz1;
    	public int Tezaurusz1 
    	{ 
    		get { return _tezaurusz1; } 
    		set
    		{
    			if (value != _tezaurusz1) {
    				_tezaurusz1 = value;
    				 OnPropertyChanged("Tezaurusz1");
    			}
    		} 
    	}
    
        private Nullable<int> _sUPER_TYPE_ID;
    	public Nullable<int> SUPER_TYPE_ID 
    	{ 
    		get { return _sUPER_TYPE_ID; } 
    		set
    		{
    			if (value != _sUPER_TYPE_ID) {
    				_sUPER_TYPE_ID = value;
    				 OnPropertyChanged("SUPER_TYPE_ID");
    			}
    		} 
    	}
    
        private Nullable<int> _bASE_ID;
    	public Nullable<int> BASE_ID 
    	{ 
    		get { return _bASE_ID; } 
    		set
    		{
    			if (value != _bASE_ID) {
    				_bASE_ID = value;
    				 OnPropertyChanged("BASE_ID");
    			}
    		} 
    	}
    
        private string _tragyszo;
    	public string Tragyszo 
    	{ 
    		get { return _tragyszo; } 
    		set
    		{
    			if (value != _tragyszo) {
    				_tragyszo = value;
    				 OnPropertyChanged("Tragyszo");
    			}
    		} 
    	}
    
        private string _magyarazat;
    	public string Magyarazat 
    	{ 
    		get { return _magyarazat; } 
    		set
    		{
    			if (value != _magyarazat) {
    				_magyarazat = value;
    				 OnPropertyChanged("Magyarazat");
    			}
    		} 
    	}
    
    }
}
